trigger:
- main

name: Deploy Bicep files

parameters:
- name: azureServiceConnection
  type: string
  default: 'RavlSandbox'

variables:
  vmImageName: 'ubuntu-latest'
  resourceGroupName: 'cristiantest1'
  location: 'eastus'
  templateFile: './main.bicep'
  csmParametersFile: './main.bicepparam'

pool:
  vmImage: $(vmImageName)

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'RavlSandbox'
    subscriptionId: '8fea7198-f8f8-4817-9b2d-14fec431c99b'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(resourceGroupName)'
    location: '$(location)'
    templateLocation: 'Linked artifact'
    csmFile: '$(templateFile)'
    csmParametersFile: '$(csmParametersFile)'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'